# Generated by Django 4.2.10 on 2024-03-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdId', models.CharField(max_length=20)),
                ('totalViews', models.IntegerField()),
                ('todayViews', models.IntegerField()),
                ('promoStatus', models.CharField(max_length=6)),
            ],
        ),
    ]
